runtime: python27
api_version: 1
threadsafe: true
service: resource

handlers:
- url: /static
  static_dir: static/
- url: /_ah/api/.*
  script: main.api


# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
#libraries:
#- name: MySQLdb
#  version: 1.2.5
libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11
- name: protorpc
  version: 1.0

# Google App Engine limits application deployments to 10,000 uploaded files per
# version. The skip_files section allows us to skip virtual environment files
# to meet this requirement. The first 5 are the default regular expressions to
# skip, while the last one is for all env/ files.
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
- ^(.*/)?setuptools/script \(dev\).tmpl$

env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud service-management deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: rmp-sandbox.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2017-09-14r1